
required = [
  "github.com/client9/misspell/cmd/misspell",
  "golang.org/x/tools/cmd/goimports",
  "github.com/golang/dep/cmd/dep",
]

[[constraint]]
  name = "golang.org/x/tools"
  revision = "4c874b978acba4ecd4a257d3bb8829dd5de17be8"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.3.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
