apiVersion: batch/v1
kind: Job
metadata:
  generateName: send-event-
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: send-event
        image: github.com/mattmoor/knobots/cmd/send-event
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Never
  backoffLimit: 0
