apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: misspell-knative-eventing-
  namespace: default
spec:
  taskRef:
    name: misspell
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/knative/eventing.git
    params:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: eventing
    - name: ASSIGNEE
      value: n3wscott
