apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  generateName: misspell-knative-eventing-operator-
  namespace: default
spec:
  source:
    git:
      url: https://github.com/knative/eventing-operator.git
      revision: master
  template:
    name: misspell
    arguments:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: eventing-operator
