apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: misspell-knative-sample-controller-
  namespace: default
spec:
  taskRef:
    name: misspell
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/knative/sample-controller.git
    params:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: sample-controller
    - name: ASSIGNEE
      value: n3wscott
