apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: prettier-knative-test-infra-
  namespace: default
spec:
  taskRef:
    name: prettier
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/knative/test-infra.git
    params:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: test-infra
    - name: ASSIGNEE
      value: chaodaig
