apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: prettier-tekton-triggers-
  namespace: default
spec:
  taskRef:
    name: prettier
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/tektoncd/triggers.git
    params:
    - name: ORGANIZATION
      value: tektoncd
    - name: REPOSITORY
      value: triggers
    - name: ASSIGNEE
      value: ImJasonH
