apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  generateName: update-pkg-knative-serving-
spec:
  source:
    git:
      url: https://github.com/knative/serving.git
      revision: master
  template:
    name: dep-update
    arguments:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: serving
    - name: DEPENDENCY
      value: github.com/knative/pkg
