apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  generateName: update-deps-knative-sample-controller-
spec:
  source:
    git:
      url: https://github.com/knative/sample-controller.git
      revision: master
  template:
    name: dep-update
    arguments:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: sample-controller
    - name: DEPENDENCIES
      value: github.com/knative/test-infra knative.dev/pkg
    - name: ASSIGNEE
      value: mattmoor
