apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: commitstatus-trigger
  namespace: default
spec:
  filter:
    sourceAndType:
      type: dev.mattmoor.knobots.commitstatus
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: commitstatus-bot
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: commitstatus-bot
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: github.com/mattmoor/knobots/cmd/commitstatus
        env:
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              # This bot uses a different secret because it needs more permissions
              # in order to write the repo status.
              name: github-hook-secret
              key: accessToken
