apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: copyright-trigger
  namespace: default
spec:
  filter:
    sourceAndType:
      type: dev.mattmoor.knobots.reviewrequest
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: copyright-bot
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: copyright-bot
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: github.com/mattmoor/knobots/cmd/copyright
        env:
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-comment-secret
              key: accessToken
