apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: dep-update
spec:
  parameters:
  - name: ORGANIZATION
  - name: REPOSITORY
  - name: DEPENDENCY
  - name: ASSIGNEE
    default: mattmoor

  steps:
  - name: dep
    image: gcr.io/convoy-adapter/dep
    command: ["/bin/bash", "-c"]
    args:
    - |
      set -e
      set -x
      mkdir -p ${GOPATH}/src/github.com/${ORGANIZATION}/
      ln -s /workspace ${GOPATH}/src/github.com/${ORGANIZATION}/${REPOSITORY}
      cd ${GOPATH}/src/github.com/${ORGANIZATION}/${REPOSITORY}
      go get -u github.com/google/licenseclassifier
      dep ensure -update ${DEPENDENCY}
      # Sometimes we "fix up" ./vendor, so run this for good measure.
      ./hack/update-deps.sh
      # TODO(mattmoor): Consider this ./hack/update-codegen.sh
    env:
    - name: GOPATH
      value: /tmp/go

  - name: open-pull-request
    image: github.com/mattmoor/knobots/cmd/pr-builder
    args:
    - "-organization=${ORGANIZATION}"
    - "-repository=${REPOSITORY}"
    - "-title=Update ${DEPENDENCY} dependency"
    - "-body"
    - |
        Produced via:
          `dep ensure -update ${DEPENDENCY}`
        /assign @${ASSIGNEE}
    env:
    - name: GITHUB_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-comment-secret
          key: accessToken
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-comment-secret
          key: username
    # Inject the generated pod name so that we can use it as a
    # pseudo-random branch name (and associate open PRs with
    # build logs).
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
