# apiVersion: eventing.knative.dev/v1alpha1
# kind: Trigger
# metadata:
#   name: triage-pr-trigger
#   namespace: default
# spec:
#   filter:
#     sourceAndType:
#       type: dev.knative.source.github.pull_request
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1alpha1
#       kind: Service
#       name: triage-bot
# ---
# apiVersion: eventing.knative.dev/v1alpha1
# kind: Trigger
# metadata:
#   name: triage-issues-trigger
#   namespace: default
# spec:
#   filter:
#     sourceAndType:
#       type: dev.knative.source.github.issues
#   subscriber:
#     ref:
#       apiVersion: serving.knative.dev/v1alpha1
#       kind: Service
#       name: triage-bot
# ---
# apiVersion: serving.knative.dev/v1alpha1
# kind: Service
# metadata:
#   name: triage-bot
  # labels:
  #   serving.knative.dev/visibility: cluster-local
# spec:
#   template:
#     spec:
#       containers:
#       - image: github.com/mattmoor/knobots/cmd/triage
#         env:
#         - name: GITHUB_ACCESS_TOKEN
#           valueFrom:
#             secretKeyRef:
#               name: github-comment-secret
#               key: accessToken
