apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: dep-update
spec:
  parameters:
  - name: ORGANIZATION
  - name: REPOSITORY
  - name: DEPENDENCIES
  - name: BRANCH
    default: master
  - name: ASSIGNEE
    default: mattmoor

  steps:
  - name: dep
    image: gcr.io/mattmoor-knative/dep
    command: ["/bin/bash", "-c"]
    resources:
      requests:
        cpu: 3000m
        memory: 2Gi
    args:
    - |
      set -e
      set -x
      export PARENT_DIR=${GOPATH}/src/github.com/${ORGANIZATION}
      if [ "${REPOSITORY}" == "pkg" ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      elif [ "${REPOSITORY}" == "sample-controller" ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      elif [ "${REPOSITORY}" == "test-infra" ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      elif [ "${REPOSITORY}" == serving ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      elif [ "${REPOSITORY}" == eventing ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      elif [ "${REPOSITORY}" == eventing-contrib ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      elif [ "${REPOSITORY}" == "caching" ]
      then
        export PARENT_DIR=${GOPATH}/src/knative.dev
      fi
      mkdir -p ${PARENT_DIR}
      ln -s /workspace ${PARENT_DIR}/${REPOSITORY}
      cd ${PARENT_DIR}/${REPOSITORY}
      export REPO_ROOT_DIR=${PARENT_DIR}/${REPOSITORY}
      dep ensure -update ${DEPENDENCIES}
      go get -u github.com/google/licenseclassifier
      go get -u github.com/knative/test-infra/tools/dep-collector
      export PATH=${PATH}:${GOPATH}/bin
      # Sometimes we "fix up" ./vendor, so run this for good measure.
      ./hack/update-deps.sh
      # We may pull in code-generator updates.
      ./hack/update-codegen.sh
    env:
    - name: GOPATH
      value: /tmp/go

  - name: open-pull-request
    image: github.com/mattmoor/knobots/cmd/pr-builder
    args:
    - "-organization=${ORGANIZATION}"
    - "-repository=${REPOSITORY}"
    - "-title=Auto-update dependencies"
    - "-branch=${BRANCH}"
    - "-body"
    - |
        Produced via:
          `dep ensure -update ${DEPENDENCIES}`
        /assign ${ASSIGNEE}
    env:
    # Inject the generated pod name so that we can use it as a
    # pseudo-random branch name (and associate open PRs with
    # build logs).
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

    # This mimics the runtime contract of the GithubBinding
    volumeMounts:
    - name: github-binding
      mountPath: /var/bindings/github

  volumes:
  - name: github-binding
    secret:
      secretName: github-comment-secret
