apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: misspell
spec:
  inputs:
    params:
    - name: ORGANIZATION
    - name: REPOSITORY
    - name: BRANCH
      default: master
    - name: ASSIGNEE
      default: mattmoor
    resources:
    - name: source
      type: git

  steps:
  - name: misspell
    image: github.com/mattmoor/knobots/vendor/github.com/client9/misspell/cmd/misspell
    # We override the entrypoint of the ko image to embed shell functionality.
    command: ["/bin/bash", "-c"]
    args: ["/ko-app/misspell -w $(find -name '*.go' | grep -v vendor)"]

  - name: open-pull-request
    image: github.com/mattmoor/knobots/cmd/pr-builder
    args:
    - "-workspace=/workspace/source"
    - "-organization=$(inputs.params.ORGANIZATION)"
    - "-repository=$(inputs.params.REPOSITORY)"
    - "-title=Fix spelling errors"
    - "-branch=$(inputs.params.BRANCH)"
    - "-body"
    - |
        Produced via:
          `github.com/client9/misspell`
        /assign $(inputs.params.ASSIGNEE)
        /cc $(inputs.params.ASSIGNEE)

    env:
    # Inject the generated pod name so that we can use it as a
    # pseudo-random branch name (and associate open PRs with
    # build logs).
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

    # This mimics the runtime contract of the GithubBinding
    volumeMounts:
    - name: github-binding
      mountPath: /var/bindings/github

  volumes:
  - name: github-binding
    secret:
      secretName: github-comment-secret
