apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: prettier

spec:
  inputs:
    params:
    - name: ORGANIZATION
    - name: REPOSITORY
    - name: BRANCH
      default: master
    - name: ASSIGNEE
      default: mattmoor
    resources:
    - name: source
      type: git

  steps:
  - name: prettier
    image: gcr.io/mattmoor-knative/prettier
    # We override the entrypoint of the ko image to embed shell functionality.
    command: ["/bin/sh", "-c"]
    args: ["prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)"]

  - name: open-pull-request
    image: github.com/mattmoor/knobots/cmd/pr-builder
    args:
    - "-workspace=/workspace/source"
    - "-organization=$(inputs.params.ORGANIZATION)"
    - "-repository=$(inputs.params.REPOSITORY)"
    - "-title=Format markdown"
    - "-branch=$(inputs.params.BRANCH)"
    - "-body"
    - |
        Produced via:
          `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
        /assign $(inputs.params.ASSIGNEE)
        /cc $(inputs.params.ASSIGNEE)

    env:
    # Inject the generated pod name so that we can use it as a
    # pseudo-random branch name (and associate open PRs with
    # build logs).
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

    # This mimics the runtime contract of the GithubBinding
    volumeMounts:
    - name: github-binding
      mountPath: /var/bindings/github

  volumes:
  - name: github-binding
    secret:
      secretName: github-comment-secret
    
